# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SDWebImage_Note' do

   pod 'SDWebImage', '~> 3.7.2'

end

target 'SDWebImage_NoteTests' do

end

target 'SDWebImage_NoteUITests' do

end

